### ISSUE TITLE
[Web Security] Project 3: Forgery, Theft, and Hijacking Prevention

### ISSUE THREAD

**Issue by maydewd** [maydewd/globitek-session#1]
My app is complete, please review. /cc @codepathreview @codepath

**Comment by melophonic** [comment]
Excellent work, @maydewd. The only issue I was able to find is that it appears you did not add `require_login();` directive to the `staff/territories` pages, though it's clear from your whitelisting/blacklisting answer that you understand this well. I appreciate the clear notes about the decisions you made regarding login error messages, as well as the issues you found with the code. Very well done.

**Comment by maydewd** [comment]
Thanks for the feedback @melophonic. I fixed those few (unintentional) examples of the pitfalls of blacklisting :).
